
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=musicplayer
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: musicplayer
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 
    external: true
    name: 49458bde750620d8887a2f7fe0ed5ed0bd71fc7554a34ae87751df0b13407289
